; payload
;  exec: ssDNA
;  type: virus
;  desc:
;   Adeno-associated virus, infects humans but doesn't cause any disease.
;   Is a perfect for carrying payloads (e.g. vector vaccine)
;  related:

; this is the Adeno-associated virus
; taken from https://www.ncbi.nlm.nih.gov/nuccore/KX583629.1

; the first thing we have is a repeating region
; 1..174
bases gtcatactttctcacaataagcttgtcctcctccccccaataacacgctcgctcgctcgctcgggacaaccgggcgaagcccggttgcaagcgcccttcgggcgcttgtcccgagcgagcgagcgagcgtgttattggggggaggaggacaagcttattgtgagaaagtatga

; padding
; 175..430
bases ccaaagtacgtaggccagataccgtaggggttacacaaccaggttgtaacacttgggtgtctgggttcgatttccagtctggccgtgtagggagggcgtgattcttcatcaaagtggtgggtggagaatctgacccttcttttttctcgcgagactttgcgagatttccaaatatcgcgagaccttaacagtataaagtgagcgcgagcgagcgaccgcgccagacgccatcacgccgttgatccctacacaccaa

; this is the reproduction protein
; this is nonstructural
; 431..2377
bases gatgacgacacctacgtactacgagctgattgtggagctgccgagcgacattgacactcaactccccctggtcagcgacagctttgtgcgatgggtgacgagcaagacgtgggaaccccccctggacagcaaatgggacatggaccaagtggaccaagtccagctgactctcggagacaagattcaacgggaaattttaaaacagtggaggaccattaccggagaccctgatccgaaatattacgtccagctggagcaaggagagacgtactttcacctgcacacgttgctgcagtgctgcaacattaagccgttggtcctcggaagatatgtcaaacagattgagaaaaagctggtgagtaccgtctacggggggcacaatcctctgatcgacaattggctccgaattaccaagacaaaatcgatcgggggctccaataaaattcgcgcgcaaagctacattcccgcctatctcattcccaaaaaacaaccggaagttcagtgggcgtggacaaatatcgaggagtatataaaggccgttttaaactctgaattgcgtcatcaaattggagaagcgcatttccaggagcaaggcctcgctctgcgcgacagcaccaacctatcgagaaactctgagggggctcccatcatcgtcagcaagtgcaccaagaaatacatggagctcgtcgagtggctggtcgagaagggcatcacgaccgagaagcaatggctcttggaaaacaaggagagctttcgctccttccaggcctcgagcaactcggctcgccaaatcaaggcggcccttcagggcgccactcaggaaatgctcctcaccaagacggcgtcagactacctgattggcaaagaccccatcggagacatgaccgacaaccgaatctacaaaattttggaaatgaacggctacgaccctctctacgtggccaacctgtttgtaggttggtgtcagatgaagtttggaaaacgaaacacaatctggctgtttggacctgcgaccacgggcaagaccaacattgcggaggctattgcccatgctgtgcccttttatggatgcgtcaactggaccaacgaaaactttcccttcaacgactgcctggaaaagatgatcatttggtgggaagaggggaaaatgacggccaagattgtagagacggctaaagccatcctcgggggatccaaggttcgcgtcgaccaaaagtgcaagtcttcgatgcagctggaacctacgccggtcatcattaccagcaacaccaacatgtgttatgtcgtggatggaaacacgaccacctttgagcacgctcaacccctacaggaccgaatgtttaagctggaactcttgaagcgacttcccgacgactttggaaaagtgaccaaaaaggaagtcagagactttttcgcgtggggggctaaacataccgtagaggtcgattcttgctttttagtaagaaaggcggagtctcgtaaaagacacgccccggaagtggcatcagaggataaaagccctcccgctaaggcggctcgcacagacgagcttcagcatttgagcggcgaggagggaacctctgtctctgccaggtatgttttgaaatgcgctaaacatttggggatggtaaccatgatgtggccatgtagagattgtgaaaaggccaattgtaatataaatcagtgcattttgcataaaagtttgtcttgtaaagagtgttttccagattatgattccgatgtatctgttcaggaaggcgagccttccggcaacccccccttgtcgagctccgacgaggacattccctctcaccaacccccccttgtcaaagattgtaaaccctggactccgtgttcctatcaccacctgaccggggtagccaatagaaattgtagcatgtgcaaattgagaaatgtggatttggatgattgtgacagtgagcaata

; padding
; 2378..2394
bases aaatgacttaaactagac

; this is the capsid protein
; 2395..4611
bases atgtctgctgctgattctgttccagattggttggagaattttgtgcgcaagcacattgtcaatccggttgccgaatttgctcatttggaggctggagccccacaaccaaagcctaaccagcagcatcaagatcgaggcggaaccaaggacgatagccgaggtcttgttttacctggctacaagtatcttggtccttttaacggtcttgacaagggtgaacccgtcaacgctgctgacgctgctgcgctcgagcacgacaaggcgtacgaccagcagctgcaagcgggagacaacccctatctgaaatataaccacgcagacgccgaatttcaagaggccctaaaggacgacacatcctttgggggaaatctcggtaaagcggtattccaggccaaaaagagggttctcgaaccctttggcttggctgaagacggaaagacggctcctaccaacgaacgtcgaaaggagaatatagacgactactatcccaagaggaaaaaagccaaggcgggagaagaaaagcccccttctaccgacgcagtagaaggagctggagacggagaaccaagcacatctaccggaggggaaacccccagcggtactcaatctaatacaatgtctgcagggggcggcgcaccaatgggcgatgaccaacagggtgccgatggagtgggtaattcctcgggaaattggcattgcgattccacatggctggacaatcttgtcatcaccaagtccacccgaacctgggtcctgcccagctacaacaaccacatctacaagcgagtctccaacacgggaggagacaactcgtactttggattcagcaccccgtggggatactttgactttaaccgattccactgccacttttcaccgcgagactggcaacggctcatcaacaacaactggggaatccgacccaaggccctcaagtttaagctcttcaacatccaagtcaaagaggtcacgactcaagactcgaccaagaccgtcgccaataacctcaccagcactattcaagtctttgcggactcggaatatcagctaccgtatgtagtgggcaacgcgtccgagggatgcctgcctccctttcccgcggacgtctttgtgctgccgcagtacggatacctgactttggacaataacggaaactctgtcgacagaagcgccttttactgtctcgagtactttccgagtcagatgctgagaacgggcaacaattttgaatttacctacgaatttgaaaaggtgccgttccacagcatgtttgctcacaaccagtcgctgagtcggctaatgaatccgttggtggaccagtacttgtactactttagcaacgtctcggggcctaacaacgctgcccagattcgttacgacaagggtcgtaaggaagacattgccggccaatgcagaaattggctccccggaccattttggcaaaatcagagcgtgcgtctggacaatgccaacaacaatcccaagtgggattactgggcaaactcgaatcgagtaaggctggacggcaaattgtactccgtcaaccctggaattcctcaagccacagaagctacgcagaatccctacaaccagtatccgacgcagtcgactctggtgtttgaaaagaagcccggaggaaaccccaccggagtagatccaaacaatctcaaccttaccaaggatgaagaaattagaaccaccaatcccgtggcctatgccgtgtcaggaacagtcaccggaacgtcggccatcaatcaaaacaatggagccagtcagactcctacggcttccgacgtggacattttgggagccatgcccggaatggtgtggcaaaatagagacatttatctgcaagggcccatttgggccaagattccctccacagacaatcattttcatccttgtcctctcatgggaggattcggattcaagcatccgcctccgcagattctcatcaaaaacacaccggtgccgtcagaccctgcgggattttcagcgaccaagttcaactcgttcatcactcagtattccaccggacaagtcaccgtggaaatcatgtgggaactacaaaaggaaacgtccaagaggtggaatccagaaattcagtttacgtccaatttcaacgccacccaagaactgcagtttgcacccaacgtgtctggagactacgaagaacccagagccatcggctcgagatatctcaccaaacctctgtaa

; padding
; 4612..4683
bases cttgtatttattcattgtttgtatcatttattcaataaaccgtttattcgtttcagtttcaattcgactcgc

; padding
; 4684..4847
bases gtcatactttctcacaataagcttgtcctcctccccccaataacacgctcgctcgctcgctcgggacaagcgcccgaagggcgcttgcaaccgggcttcgcccggttgtcccgagcgagcgagcgagcgtgttattggggggaggaggacaagcttattgtgagaaagtatga

; I don't know why this is here tbh
bases c
